# Define the build command (replace with your specific command)
[build]
  command = "CI=false npm run build"

# Set the publish directory (location of generated deploy files)
publish = "public"

# Environment variable (replace with your variable name and value)
[env]
  REACT_APP_TEST = "your_value_here"